### PR TITLE
Fix 'chr' function and tpy compilation

### PR DESCRIPTION
**Pull request by Wiguwbe**
In a quest to make a shared library and embed tinypy, I found some errors on tpy compilation and string management.

With these changes, tpy should work (only did a quick test).

The 'chr' function now creates a "true" string object, which allows for the '\0' string/chr. The implementation could be better tho.

Also added to the makefile an option to make a shared library.

### CODE REVIEW

**Comment by Wiguwbe** [comment]
tpy is still erroneous, somehow "detecting" a false EOF/IEOF, working on that

**Comment by rainwoodman** [comment]
Hi, Sorry this slipped from my mailbox.

I am a bit confused about 617cf46. The original form with tp_string_atom also creates a real string object that ends with '\0'. (the chars array is an array of nul terminated strings). Did you run into a crash with the old version?

**Comment by rainwoodman** [comment]
Adding true python 3 like keyword argument support needs an overhaul of how argument is passed. 
Last time I visited this, I haven't been able to make a decision what to minimally support. I think we could only support a 'closed' subset of Python 3 cases -- but enumerating the cases has been a bit laborring. I'll think about this more.

This file contains a list of currently supported and unsupported keyword argument + positional argument combinations:
https://github.com/rainwoodman/tinypy/blob/master/tests/test_args.py#L36

**Comment by rainwoodman** [comment]
Finally, would you be able to write down a script for you to test the .so target? (It sounds like you do have something for reproducing https://github.com/rainwoodman/tinypy/pull/13#issuecomment-734459123)

**Comment by Wiguwbe** [comment]
Hey, no problem.
I have a small "issue" with contextualization when I'm explaining something, working on that :smile: 

The chr function, as it was with tp_string_atom, when calculation the length on the string,it would give false values when the char ordinal is <32 (special chars), namely the '\0' (which reports a length of 0) and '\x03' (end of text) or '\x04' (end of transmission) which was also causing concatenated strings to give false lengths (I can't really recall what was the exact problem). It was causing problems on the "compilation" of the bytecode, when concatenating 4 bytes into a word, reporting false lengths.
With the tp_string_t (python string, i take it), the length is known from the beginning, hence discarding the need for strlen.

Regarding keyworded arguments, I saw the known_ tests on them, I guess supporting a subset of python3 is totally acceptable.
It was causing the false EOF, fixed on a13bb686d442ce3fe61b85af93a53b11a0ba66dd. Due to keyword argument not being passed correctly, the `eof=False` was being seeing inside the function as a dict `R{eof: True}`, which evaluates to True and was far from intended. That commit removes the keyword from the calling.

The .so build works fine and the linkage and embedding as well, I'll make a script of a simple test.

With these changes, is possible to run a script from `tpy <script.py>`.

(Sorry for long post)

**Comment by Wiguwbe** [comment]
Forgot to push this latest commit, if you set the environment  variable `TPY=1` and run the tests, `TPY=1 make tests`, it shall use the tpy binary to run the tests (instead of tpc/python).

**Comment by rainwoodman** [comment]
Thanks for the explanations. 

The chr issue seems to be related to more relating to encoding decoding of strings and bytes. 
An atomic string is NUL terminated, thus we run strlen on it. I can't really picture how this could happen.
Atomic strings are used else where too, and I am concerned if they should be affected as well.

If I run the TPY=1 tests without 617cf46 it should crash?

**Comment by Wiguwbe** [comment]
It should. The problem, from what I recall, was on tinypy/encode.py, inside the map_tags function, on the last for loop. It was raising the exception.

**Comment by rainwoodman** [comment]
Indeed. It is because '\0" as an atom is counted as 0 length rather than 1 -- there is a cleaner way to fix the atoms, we should have cached the objects directly directly anyway.

Could you rebase (to e30f83fee4545fb0191a6f085b7d8ade537a299c), and drop the tpy_string patch? (I can probably also do this from my side).

**Comment by Wiguwbe** [comment]
Seems cleaner indeed, I'll rebase in the morning.

**Comment by rainwoodman** [comment]
Sure. I have another commit that changes TPY=1 to --backend=tpy as a follow up.

**Comment by Wiguwbe** [comment]
Okay, sorry about the commit mess, conflicts on 'chr' are resolved now.

**Comment by rainwoodman** [comment]
Thanks!

**Pull request merged**
